# Generated by Django 2.1.1 on 2018-11-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AmountofGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountofGroup', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=100)),
                ('groups', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GradeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradestatus', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupOfSubject', models.CharField(default='Programming', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('gender', models.CharField(default='', max_length=10)),
                ('studentsId', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('academicYears', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.AcademicYears')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentStatus', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectNumber', models.CharField(default='', max_length=100)),
                ('subjectName', models.CharField(default='', max_length=100)),
                ('credit', models.IntegerField(default='')),
                ('curriculumLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.CurriculumLevel')),
                ('groupOfSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.GroupOfSubject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectYearStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.Subjects')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.AcademicYears')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.UserType'),
        ),
        migrations.AddField(
            model_name='students',
            name='studentStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.StudentStatus'),
        ),
        migrations.AddField(
            model_name='grade',
            name='gradestatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.GradeStatus'),
        ),
        migrations.AddField(
            model_name='grade',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.Students'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.Subjects'),
        ),
        migrations.AddField(
            model_name='curriculumlevel',
            name='levelEdu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.LevelEducation'),
        ),
    ]
