# Generated by Django 2.1.1 on 2018-11-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyzeGrade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeUserStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default='', max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('studentID', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('academicYear', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.User')),
            ],
        ),
        migrations.AddField(
            model_name='gradeuserstudent',
            name='userStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalyzeGrade.UserStudent'),
        ),
    ]
